apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: cpu-stress-test
  namespace: chaos-testing
spec:
  mode: one
  selector:
    namespaces:
      - sock-shop
    labelSelectors:
      name: catalogue   
  stressors:
    cpu:
      workers: 2
  duration: "6m"
